Dev bootcamp
LEuLuDyHa/app pull request #7
Opened 2023-02-26 15:26 UTC by WollfieGitHub

This adds the code generated by Android Studio using the Material3 + JetpackCompose Empty Activity preset.

The only modified code is in src/ and androidTest/, according to the Week 1 Bootcamp

2023-02-26 16:01 UTC, Lynoxe requested changes
I would suggest to add test tags directly to the interesting components rather than the column containing them. It would be more robust if we change the UI organisation (for example add a second element in the column between the `TextField` and the `Button`. Furthermore it would make the tests more self-explanatory (currently we don't know, by reading only the tests, that `column.onChildAt(0)` is the `TextField` for example). Having two separate test tags such as "UsernameField" and "StartButton" for example would be clearer.

2023-02-26 16:03 UTC, Lynoxe reviewed
I like the `object DeclaredIntents`, I didn't think about that myself.

2023-02-26 16:04 UTC, Lynoxe reviewed
The TextField isn't visible before we click on it, maybe add some background color or some indicator in some way would be nice.
However as this is only a sample scene that we'll remove it doesn't really matter for now.

2023-02-26 22:19 UTC, Lynoxe requested changes
Add the .idea folder to the .gitignore (I think it isn't important, just annoying)

2023-02-27 12:15 UTC, Lynoxe commented on app/src/main/java/com/github/leuludyha/ibdb/GreetingActivity.kt
> +    }
I like this way to handle the intents extras, I didn't think about it!

2023-02-27 12:39 UTC, Lynoxe approved these changes
LGTM

2023-02-27 13:24 UTC, HanaFarid approved these changes
LGTM!

2023-02-27 13:29 UTC, merged